//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orderwise.Calculator.Web.CalculatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorServiceReference.ICalculatorService")]
    public interface ICalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/CalculateValue", ReplyAction="http://tempuri.org/ICalculatorService/CalculateValueResponse")]
        string CalculateValue(string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/CalculateValue", ReplyAction="http://tempuri.org/ICalculatorService/CalculateValueResponse")]
        System.Threading.Tasks.Task<string> CalculateValueAsync(string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/GetSquareRoot", ReplyAction="http://tempuri.org/ICalculatorService/GetSquareRootResponse")]
        string GetSquareRoot(string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/GetSquareRoot", ReplyAction="http://tempuri.org/ICalculatorService/GetSquareRootResponse")]
        System.Threading.Tasks.Task<string> GetSquareRootAsync(string expression);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServiceChannel : Orderwise.Calculator.Web.CalculatorServiceReference.ICalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<Orderwise.Calculator.Web.CalculatorServiceReference.ICalculatorService>, Orderwise.Calculator.Web.CalculatorServiceReference.ICalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CalculateValue(string expression) {
            return base.Channel.CalculateValue(expression);
        }
        
        public System.Threading.Tasks.Task<string> CalculateValueAsync(string expression) {
            return base.Channel.CalculateValueAsync(expression);
        }
        
        public string GetSquareRoot(string expression) {
            return base.Channel.GetSquareRoot(expression);
        }
        
        public System.Threading.Tasks.Task<string> GetSquareRootAsync(string expression) {
            return base.Channel.GetSquareRootAsync(expression);
        }
    }
}
